// ═══════════════════════════════════════════════════════════════
//  DATA.JS — All item data + image map
//  img: slug used to build fextralife image URL
//  https://eldenring.wiki.fextralife.com/file/Elden-Ring/<img>_elden_ring_wiki_guide_200px.png
// ═══════════════════════════════════════════════════════════════

const IMG_BASE = "https://eldenring.wiki.fextralife.com/file/Elden-Ring/";
const IMG_SUFFIX = "_elden_ring_wiki_guide_200px.png";

function itemImg(slug) {
  return IMG_BASE + slug + IMG_SUFFIX;
}

const CATEGORIES = [
  { id:'talismans',    key:'cat_talismans',    icon:'🔮' },
  { id:'weapons',      key:'cat_weapons',      icon:'⚔️' },
  { id:'armor',        key:'cat_armor',        icon:'🛡️' },
  { id:'sorceries',    key:'cat_sorceries',    icon:'✨' },
  { id:'incantations', key:'cat_incantations', icon:'🌟' },
  { id:'spiritashes',  key:'cat_spiritashes',  icon:'👻' },
  { id:'shields',      key:'cat_shields',      icon:'🪖' },
];

const ITEMS = {
talismans:[
  {name:"Ancestral Spirit's Horn",effect:"Ripristina FP sconfiggendo nemici",loc:"Ancestral Woods – spirit ashes",dlc:"Base",img:"ancestral_spirits_horn_talisman"},
  {name:"Arrow's Reach Talisman",effect:"Aumenta la gittata degli archi",loc:"Dragonbarrow – Fort Faroth area",dlc:"Base",img:"arrows_reach_talisman"},
  {name:"Arrow's Soaring Sting Talisman",effect:"+50% gittata arco, +8% danno frecce",loc:"Fog Rift Fort – torre baule",dlc:"SotE",img:"arrows_soaring_sting_talisman"},
  {name:"Arsenal Charm",effect:"+15% carico massimo equipaggiamento",loc:"Raya Lucaria – Mooseman",dlc:"Base",img:"arsenal_charm_talisman"},
  {name:"Arsenal Charm +1",effect:"+17% carico massimo equipaggiamento",loc:"Altus Plateau – Seethewater Cave",dlc:"Base",img:"arsenal_charm_1_talisman"},
  {name:"Assassin's Cerulean Dagger",effect:"I colpi critici ripristinano FP",loc:"Black Knife Catacombs – boss",dlc:"Base",img:"assassins_cerulean_dagger_talisman"},
  {name:"Assassin's Crimson Dagger",effect:"I colpi critici ripristinano HP",loc:"Deathtouched Catacombs – boss",dlc:"Base",img:"assassins_crimson_dagger_talisman"},
  {name:"Axe Talisman",effect:"Potenzia gli attacchi caricati",loc:"Mistwood Ruins – baule sotterraneo",dlc:"Base",img:"axe_talisman"},
  {name:"Beloved Stardust",effect:"Velocità lancio massima, +danno subito",loc:"Count Ymir – ricompensa quest",dlc:"SotE",img:"beloved_stardust_talisman"},
  {name:"Blade of Mercy",effect:"+20% ATK per 20s dopo un colpo critico",loc:"Scorched Ruins – baule",dlc:"SotE",img:"blade_of_mercy_talisman"},
  {name:"Blessed Blue Dew Talisman",effect:"Ripristina lentamente 0.5 FP/sec",loc:"Church of Benediction – statua Marika",dlc:"SotE",img:"blessed_blue_dew_talisman"},
  {name:"Blessed Dew Talisman",effect:"Ripristina 2 HP/sec",loc:"Tower of Return – baule",dlc:"Base",img:"blessed_dew_talisman"},
  {name:"Blue Dancer Charm",effect:"+ATK fisico con carico basso",loc:"Divine Tower of Limgrave",dlc:"Base",img:"blue_dancer_charm_talisman"},
  {name:"Blue-Feathered Branchsword",effect:"+20% danno fisico con HP basso",loc:"Tombsward Cave – boss reward",dlc:"Base",img:"blue-feathered_branchsword_talisman"},
  {name:"Boltdrake Talisman",effect:"+13% negazione danni fulmine",loc:"Limgrave – lago sotterraneo",dlc:"Base",img:"boltdrake_talisman"},
  {name:"Boltdrake Talisman +1",effect:"+17% negazione danni fulmine",loc:"Altus Plateau",dlc:"Base",img:"boltdrake_talisman_1"},
  {name:"Boltdrake Talisman +2",effect:"+20% negazione danni fulmine",loc:"Farum Azula",dlc:"Base",img:"boltdrake_talisman_2"},
  {name:"Boltdrake Talisman +3",effect:"+22% negazione danni fulmine",loc:"Shadow Keep – Storehouse",dlc:"SotE",img:"boltdrake_talisman_3"},
  {name:"Bull-Goat's Talisman",effect:"Aumenta la poise",loc:"Great Tunnel – Patches quest",dlc:"Base",img:"bull-goats_talisman"},
  {name:"Cerulean Amber Medallion",effect:"+7% FP massimo",loc:"Weeping Peninsula – baule",dlc:"Base",img:"cerulean_amber_medallion_talisman"},
  {name:"Cerulean Amber Medallion +1",effect:"+9% FP massimo",loc:"Raya Lucaria – baule",dlc:"Base",img:"cerulean_amber_medallion_1_talisman"},
  {name:"Cerulean Amber Medallion +2",effect:"+11% FP massimo",loc:"Mountaintops – baule",dlc:"Base",img:"cerulean_amber_medallion_2_talisman"},
  {name:"Cerulean Amber Medallion +3",effect:"+12.5% FP massimo",loc:"Scorpion River Catacombs – boss",dlc:"SotE",img:"cerulean_amber_medallion_3_talisman"},
  {name:"Cerulean Seed Talisman",effect:"+20% FP dalla Flask",loc:"Murkwater Catacombs – baule",dlc:"Base",img:"cerulean_seed_talisman"},
  {name:"Cerulean Seed Talisman +1",effect:"+30% FP dalla Flask",loc:"Finger Ruins of Dheo – campana",dlc:"SotE",img:"cerulean_seed_talisman_1"},
  {name:"Claw Talisman",effect:"Potenzia gli attacchi in salto",loc:"Stormveil Castle – torre",dlc:"Base",img:"claw_talisman"},
  {name:"Concealing Veil",effect:"Nasconde il giocatore accovacciato in movimento",loc:"Volcano Manor – Bernahl quest",dlc:"Base",img:"concealing_veil_talisman"},
  {name:"Crimson Amber Medallion",effect:"+6% HP massimo",loc:"Morne Rampart – mercante",dlc:"Base",img:"crimson_amber_medallion_talisman"},
  {name:"Crimson Amber Medallion +1",effect:"+7% HP massimo",loc:"Weeping Peninsula",dlc:"Base",img:"crimson_amber_medallion_1_talisman"},
  {name:"Crimson Amber Medallion +2",effect:"+8% HP massimo",loc:"Mohgwyn Palace",dlc:"Base",img:"crimson_amber_medallion_2_talisman"},
  {name:"Crimson Amber Medallion +3",effect:"+10% HP massimo",loc:"Fog Rift Catacombs – boss",dlc:"SotE",img:"crimson_amber_medallion_3_talisman"},
  {name:"Crimson Seed Talisman",effect:"+20% HP dalla Flask",loc:"Stormveil Castle – baule",dlc:"Base",img:"crimson_seed_talisman"},
  {name:"Crimson Seed Talisman +1",effect:"+30% HP dalla Flask",loc:"Finger Ruins of Rhia – campana",dlc:"SotE",img:"crimson_seed_talisman_1"},
  {name:"Crusade Insignia",effect:"+15% ATK per 20s dopo kill nemico",loc:"Fire Knight Queelign – drop NPC",dlc:"SotE",img:"crusade_insignia_talisman"},
  {name:"Dagmar Greatshield Talisman",effect:"Potenzia attacchi parati con scudo",loc:"Enir-Ilim – area profonda",dlc:"SotE",img:"dagmar_greatshield_talisman"},
  {name:"Dragoncrest Greatshield Talisman",effect:"+20% negazione danni fisici (Legg.)",loc:"Drainage Channel – Site of Grace",dlc:"Base",img:"dragoncrest_greatshield_talisman"},
  {name:"Dragoncrest Shield Talisman",effect:"+10% negazione danni fisici",loc:"Sages Cave",dlc:"Base",img:"dragoncrest_shield_talisman"},
  {name:"Dragoncrest Shield Talisman +1",effect:"+13% negazione danni fisici",loc:"Auriza Hero's Grave – baule",dlc:"Base",img:"dragoncrest_shield_talisman_1"},
  {name:"Dragoncrest Shield Talisman +2",effect:"+17% negazione danni fisici",loc:"Crumbling Farum Azula",dlc:"Base",img:"dragoncrest_shield_talisman_2"},
  {name:"Dried Bouquet",effect:"+15% ATK per 20s quando uno spirito alleato muore",loc:"Belurat Tower Settlement – stanza nascosta",dlc:"SotE",img:"dried_bouquet_talisman"},
  {name:"Erdtree's Favor",effect:"+3% HP, +7% Stamina, +5% Load",loc:"Fringefolk Hero's Grave – baule",dlc:"Base",img:"erdtrees_favor_talisman"},
  {name:"Erdtree's Favor +1",effect:"+3.5% HP, +8.5% Stamina, +6.5% Load",loc:"Subterranean Shunning-Grounds",dlc:"Base",img:"erdtrees_favor_1_talisman"},
  {name:"Erdtree's Favor +2",effect:"+4% HP, +10% Stamina, +8% Load (Legg.)",loc:"Leyndell Ashen Capital – albero morto",dlc:"Base",img:"erdtrees_favor_2_talisman"},
  {name:"Fine Crucible Feather Talisman",effect:"Migliora le schivate, +15% danno subito",loc:"Rauh Ruins – rami d'albero",dlc:"SotE",img:"fine_crucible_feather_talisman"},
  {name:"Flamedrake Talisman",effect:"+13% negazione danni fuoco",loc:"Gael Tunnel – boss",dlc:"Base",img:"flamedrake_talisman"},
  {name:"Flamedrake Talisman +1",effect:"+17% negazione danni fuoco",loc:"Volcano Cave – boss",dlc:"Base",img:"flamedrake_talisman_1"},
  {name:"Flamedrake Talisman +2",effect:"+20% negazione danni fuoco",loc:"Mt. Gelmir – baule",dlc:"Base",img:"flamedrake_talisman_2"},
  {name:"Flamedrake Talisman +3",effect:"+22% negazione danni fuoco",loc:"Shadow Keep – gabbie – baule",dlc:"SotE",img:"flamedrake_talisman_3"},
  {name:"Flock's Canvas Talisman",effect:"Potenzia enormemente le incantazioni",loc:"Millicent quest – Gowry's Shack",dlc:"Base",img:"flocks_canvas_talisman"},
  {name:"Godfrey Icon",effect:"Potenzia spell e skill caricate (Legg.)",loc:"Golden Lineage Evergaol – Godefroy",dlc:"Base",img:"godfrey_icon_talisman"},
  {name:"Godskin Swaddling Cloth",effect:"Attacchi ripetuti ripristinano HP",loc:"Mountaintops – Spiritcaller's Cave",dlc:"Base",img:"godskin_swaddling_cloth_talisman"},
  {name:"Gold Scarab",effect:"+20% Rune dai nemici",loc:"Abandoned Cave – boss",dlc:"Base",img:"gold_scarab_talisman"},
  {name:"Golden Braid",effect:"+22% negazione danni sacri",loc:"Scaduview – cadavere in tronco",dlc:"SotE",img:"golden_braid_talisman"},
  {name:"Graven-Mass Talisman",effect:"Potenzia enormemente le sorcery",loc:"Albinauric Rise – baule",dlc:"Base",img:"graven-mass_talisman"},
  {name:"Graven-School Talisman",effect:"Potenzia le sorcery",loc:"Raya Lucaria Academy – baule",dlc:"Base",img:"graven-school_talisman"},
  {name:"Great-Jar's Arsenal",effect:"+19% carico massimo equipaggiamento",loc:"Caelid – Great-Jar knights quest",dlc:"Base",img:"great-jars_arsenal_talisman"},
  {name:"Green Turtle Talisman",effect:"+17.7% velocità recupero stamina",loc:"Summonwater Village – baule sotterraneo",dlc:"Base",img:"green_turtle_talisman"},
  {name:"Haligdrake Talisman",effect:"+13% negazione danni sacri",loc:"Weeping Peninsula – Tombsward Cave",dlc:"Base",img:"haligdrake_talisman"},
  {name:"Haligdrake Talisman +1",effect:"+17% negazione danni sacri",loc:"Deeproot Depths – baule",dlc:"Base",img:"haligdrake_talisman_1"},
  {name:"Haligdrake Talisman +2",effect:"+20% negazione danni sacri",loc:"Haligtree – baule",dlc:"Base",img:"haligdrake_talisman_2"},
  {name:"Kindred of Rot's Exultation",effect:"Avvelenamento vicino +20% ATK",loc:"Shaded Castle – Kindred of Rot boss",dlc:"Base",img:"kindred_of_rots_exultation_talisman"},
  {name:"Lacerating Crossed-Tree",effect:"+15% ATK attacchi in scatto (PvE)",loc:"Leda – invade Hornsent quest",dlc:"SotE",img:"lacerating_crossed-tree_talisman"},
  {name:"Lord of Blood's Exultation",effect:"Bloodloss vicino +20% ATK",loc:"Mohgwyn Dynasty – Esgar boss",dlc:"Base",img:"lord_of_bloods_exultation_talisman"},
  {name:"Magic Scorpion Charm",effect:"+12% danno magico, +10% danno subito",loc:"Seluvis quest – Dolores puppet",dlc:"Base",img:"magic_scorpion_charm_talisman"},
  {name:"Marika's Scarseal",effect:"+3 Mind/Int/Faith/Arc, +10% danno subito",loc:"Siofra River – boss",dlc:"Base",img:"marikas_scarseal_talisman"},
  {name:"Marika's Soreseal",effect:"+5 Mind/Int/Faith/Arc, +15% danno subito (Legg.)",loc:"Elphael – stanza Stonesword Key",dlc:"Base",img:"marikas_soreseal_talisman"},
  {name:"Millicent's Prosthesis",effect:"+5 Dex, +ATK con attacchi rapidi",loc:"Millicent quest – guanto",dlc:"Base",img:"millicents_prosthesis_talisman"},
  {name:"Moon of Nokstella",effect:"+2 slot memoria (Legg.)",loc:"Nokstella – baule sotto statua imp",dlc:"Base",img:"moon_of_nokstella_talisman"},
  {name:"Mottled Necklace",effect:"+50 Robustezza/Immunità/Focus",loc:"Siofra Aqueduct – Valiant Gargoyle",dlc:"Base",img:"mottled_necklace_talisman"},
  {name:"Mottled Necklace +1",effect:"+75 Robustezza/Immunità/Focus",loc:"Mountaintops – baule",dlc:"Base",img:"mottled_necklace_1_talisman"},
  {name:"Mottled Necklace +2",effect:"+100 Robustezza/Immunità/Focus",loc:"Rauh Ancient Ruins – spirit spring",dlc:"SotE",img:"mottled_necklace_2_talisman"},
  {name:"Old Lord's Talisman",effect:"Estende durata effetti spell (Legg.)",loc:"Crumbling Farum Azula – baule",dlc:"Base",img:"old_lords_talisman"},
  {name:"Outer God Heirloom",effect:"+5 Arcane",loc:"Prospect Town – piccolo edificio",dlc:"SotE",img:"outer_god_heirloom_talisman"},
  {name:"Pearl Shield Talisman",effect:"+20% negazione non-fisico mentre si para",loc:"Taylew's Ruined Forge area",dlc:"SotE",img:"pearl_shield_talisman"},
  {name:"Pearldrake Talisman",effect:"+7% negazione danni non-fisici",loc:"Four Belfries – baule",dlc:"Base",img:"pearldrake_talisman"},
  {name:"Pearldrake Talisman +1",effect:"+9% negazione danni non-fisici",loc:"Wyndham Catacombs – boss",dlc:"Base",img:"pearldrake_talisman_1"},
  {name:"Pearldrake Talisman +2",effect:"+11% negazione danni non-fisici",loc:"Mountaintops – baule",dlc:"Base",img:"pearldrake_talisman_2"},
  {name:"Pearldrake Talisman +3",effect:"+11% negazione danni non-fisici",loc:"Shadow Keep Specimen Storehouse",dlc:"SotE",img:"pearldrake_talisman_3"},
  {name:"Prosthesis-Wearer Heirloom",effect:"+5 Destrezza",loc:"Millicent quest – Shaded Castle baule",dlc:"Base",img:"prosthesis-wearer_heirloom_talisman"},
  {name:"Radagon Icon",effect:"Riduce tempo lancio spell (Legg.)",loc:"Raya Lucaria Academy – balcone",dlc:"Base",img:"radagon_icon_talisman"},
  {name:"Radagon's Scarseal",effect:"+3 Vig/End/Str/Dex, +10% danno subito",loc:"Weeping Peninsula – Weeping Evergaol",dlc:"Base",img:"radagons_scarseal_talisman"},
  {name:"Radagon's Soreseal",effect:"+5 Vig/End/Str/Dex, +15% danno subito (Legg.)",loc:"Fort Faroth – cadavere sul tetto",dlc:"Base",img:"radagons_soreseal_talisman"},
  {name:"Red-Feathered Branchsword",effect:"+20% ATK con HP basso",loc:"Rose Church – Varre quest",dlc:"Base",img:"red-feathered_branchsword_talisman"},
  {name:"Rellana's Cameo",effect:"+45% ATK tenendo stance per 1s",loc:"Castle Ensis – dietro NPC Moonrithyll",dlc:"SotE",img:"rellanas_cameo_talisman"},
  {name:"Retaliatory Crossed-Tree",effect:"+17% ATK dopo schivata/backstep",loc:"Leda quest – saluto finale",dlc:"SotE",img:"retaliatory_crossed-tree_talisman"},
  {name:"Ritual Shield Talisman",effect:"+negazione fisica con HP pieno",loc:"Wyndham Ruins – baule sotterraneo",dlc:"Base",img:"ritual_shield_talisman"},
  {name:"Ritual Sword Talisman",effect:"+ATK con HP pieno",loc:"Limgrave – Deathtouched Catacombs",dlc:"Base",img:"ritual_sword_talisman"},
  {name:"Sacred Scorpion Charm",effect:"+12% danno sacro, +10% danno subito",loc:"Mountaintops – Commander Niall area",dlc:"Base",img:"sacred_scorpion_charm_talisman"},
  {name:"Shabriri's Woe",effect:"Provoca costantemente i nemici vicini",loc:"Frenzied Flame Village – Hyetta quest",dlc:"Base",img:"shabriris_woe_talisman"},
  {name:"Shard of Alexander",effect:"Potenzia enormemente le skill",loc:"Alexander quest – Iron Fist ricompensa",dlc:"Base",img:"shard_of_alexander_talisman"},
  {name:"Sharpshot Talisman",effect:"+12% potenza colpi mirati",loc:"Albinauric's Shack – baule",dlc:"SotE",img:"sharpshot_talisman"},
  {name:"Silver Scarab",effect:"Aumenta il rilevamento oggetti",loc:"Consecrated Snowfield – Hidden Path",dlc:"Base",img:"silver_scarab_talisman"},
  {name:"Smithing Talisman",effect:"+10% attacchi lanciando armi",loc:"Ruined Forge Starfall Past – cadavere",dlc:"SotE",img:"smithing_talisman"},
  {name:"Spear Talisman",effect:"Potenzia i contrattacchi con armi da punta",loc:"Weeping Peninsula – bastioni castello",dlc:"Base",img:"spear_talisman"},
  {name:"Spelldrake Talisman",effect:"+13% negazione danni magici",loc:"Sellia Crystal Tunnel",dlc:"Base",img:"spelldrake_talisman"},
  {name:"Spelldrake Talisman +1",effect:"+17% negazione danni magici",loc:"Caelid – Fort Gael",dlc:"Base",img:"spelldrake_talisman_1"},
  {name:"Spelldrake Talisman +2",effect:"+20% negazione danni magici",loc:"Mountaintops – baule",dlc:"Base",img:"spelldrake_talisman_2"},
  {name:"Spelldrake Talisman +3",effect:"+22% negazione danni magici",loc:"Castle Ensis – storeroom cadavere",dlc:"SotE",img:"spelldrake_talisman_3"},
  {name:"St. Trina's Smile",effect:"Sonno vicino → +20% ATK per 30s",loc:"Thiollier NPC – drop (ostile)",dlc:"SotE",img:"st_trinas_smile_talisman"},
  {name:"Stalwart Horn Charm",effect:"+75 Robustezza",loc:"Lenne's Rise – baule",dlc:"Base",img:"stalwart_horn_charm_talisman"},
  {name:"Stalwart Horn Charm +1",effect:"+120 Robustezza",loc:"Elphael – baule",dlc:"Base",img:"stalwart_horn_charm_1_talisman"},
  {name:"Stalwart Horn Charm +2",effect:"+180 Robustezza",loc:"Bonny Gaol – stanza Inner Jar",dlc:"SotE",img:"stalwart_horn_charm_2_talisman"},
  {name:"Stargazer Heirloom",effect:"+5 Intelligenza",loc:"Converted Fringe Tower – baule",dlc:"Base",img:"stargazer_heirloom_talisman"},
  {name:"Starscourge Heirloom",effect:"+5 Forza",loc:"Fort Gael – baule",dlc:"Base",img:"starscourge_heirloom_talisman"},
  {name:"Talisman of All Crucibles",effect:"Tutti gli effetti crucible, +45% danno subito",loc:"Ancient Ruins Grand Starway",dlc:"SotE",img:"talisman_of_all_crucibles_talisman"},
  {name:"Talisman of Lord's Bestowal",effect:"+54% poise dopo flask tears",loc:"Shadow Keep – vicino albero dorato",dlc:"SotE",img:"talisman_of_lords_bestowal_talisman"},
  {name:"Taker's Cameo",effect:"Sconfiggere nemici ripristina HP",loc:"Volcano Manor – Tanith ricompensa",dlc:"Base",img:"takers_cameo_talisman"},
  {name:"Two Fingers Heirloom",effect:"+5 Fede",loc:"Purified Ruins – baule sotterraneo",dlc:"Base",img:"two_fingers_heirloom_talisman"},
  {name:"Two-Handed Sword Talisman",effect:"+15% ATK armi a due mani",loc:"Temple Town Ruins – baule",dlc:"SotE",img:"two-handed_sword_talisman"},
  {name:"Two-Headed Turtle Talisman",effect:"+22.5% velocità recupero stamina",loc:"Grotta sotto cascata est di Rivermouth",dlc:"SotE",img:"two-headed_turtle_talisman"},
  {name:"Verdigris Discus",effect:"Carico pesante → meno danno subito",loc:"Ancient Rauh Ruins – area statua",dlc:"SotE",img:"verdigris_discus_talisman"},
  {name:"Viridian Amber Medallion",effect:"+11% Stamina massima",loc:"Tombsward – mercante",dlc:"Base",img:"viridian_amber_medallion_talisman"},
  {name:"Viridian Amber Medallion +1",effect:"+13% Stamina massima",loc:"Stormveil Castle – baule",dlc:"Base",img:"viridian_amber_medallion_1_talisman"},
  {name:"Viridian Amber Medallion +2",effect:"+15% Stamina massima",loc:"Mountaintops – area Ordina",dlc:"Base",img:"viridian_amber_medallion_2_talisman"},
  {name:"Viridian Amber Medallion +3",effect:"+17% Stamina massima",loc:"Darklight Catacombs – dopo primo imp",dlc:"SotE",img:"viridian_amber_medallion_3_talisman"},
  {name:"Warrior Jar Shard",effect:"Potenzia le skill",loc:"Volcano Manor – Alexander quest",dlc:"Base",img:"warrior_jar_shard_talisman"},
  {name:"White-Feathered Branchsword",effect:"+ATK magico con HP basso",loc:"Caria Manor – Pidia ricompensa",dlc:"Base",img:"white-feathered_branchsword_talisman"},
  {name:"Winged Sword Insignia",effect:"+ATK con attacchi consecutivi",loc:"Stillwater Cave – Cleanrot Knight boss",dlc:"Base",img:"winged_sword_insignia_talisman"},
],
weapons:[
  {name:"Blasphemous Blade",effect:"Greatsword – ripristina HP uccidendo",loc:"Enia – Ricordo del Blasfemo (Rykard)",dlc:"Base",img:"blasphemous_blade_greatsword_weapon"},
  {name:"Black Knife",effect:"Dagger – attacco silenzioso furtivo",loc:"Black Knife Catacombs – boss assassina",dlc:"Base",img:"black_knife_dagger_weapon"},
  {name:"Bloodhound's Fang",effect:"Curved Greatsword – bleed",loc:"Forlorn Hound Evergaol – boss",dlc:"Base",img:"bloodhounds_fang_curved_greatsword_weapon"},
  {name:"Bolt of Gransax",effect:"Spear – fulmine, skill Ancient Lightning Spear",loc:"Leyndell Royal Capital – freccia gigante",dlc:"Base",img:"bolt_of_gransax_spear_weapon"},
  {name:"Claymore",effect:"Greatsword – versatile, skill Lion's Claw",loc:"Mt. Gelmir – baule / Fort Gael",dlc:"Base",img:"claymore_greatsword_weapon"},
  {name:"Coded Sword",effect:"Straight Sword – danno sacro puro",loc:"Leyndell – One Crest Chamber",dlc:"Base",img:"coded_sword_straight_sword_weapon"},
  {name:"Commander's Standard",effect:"Halberd – skill potenzia truppe alleate",loc:"Commander Niall – boss reward",dlc:"Base",img:"commanders_standard_halberd_weapon"},
  {name:"Cross-Naginata",effect:"Spear – bleed, ottimo scaling Dex",loc:"Gael Tunnel – baule",dlc:"Base",img:"cross-naginata_spear_weapon"},
  {name:"Death's Poker",effect:"Greatsword – fuoco fantasma ghostflame",loc:"Leyndell – Spirit Jelly baule",dlc:"Base",img:"deaths_poker_greatsword_weapon"},
  {name:"Dragon King's Cragblade",effect:"Heavy Thrusting Sword – fulmine drago",loc:"Dragonlord Placidusax – boss reward",dlc:"Base",img:"dragon_kings_cragblade_heavy_thrusting_sword_weapon"},
  {name:"Dragonscale Blade",effect:"Katana – skill gelo drago",loc:"Nokstella – dragonkin soldier boss",dlc:"Base",img:"dragonscale_blade_katana_weapon"},
  {name:"Eclipse Shotel",effect:"Curved Sword – infligge Death blight",loc:"Castle Sol – baule",dlc:"Base",img:"eclipse_shotel_curved_sword_weapon"},
  {name:"Fallingstar Beast Jaw",effect:"Colossal – gravità, poise crusher",loc:"Altus Plateau – Full-Grown Fallingstar Beast",dlc:"Base",img:"fallingstar_beast_jaw_colossal_weapon_weapon"},
  {name:"Flamberge",effect:"Greatsword – bleed, fire",loc:"Caelid – Redmane Knight drops",dlc:"Base",img:"flamberge_greatsword_weapon"},
  {name:"Godslayer's Greatsword",effect:"Colossal Sword – black flame skill",loc:"Divine Tower of Caelid – baule",dlc:"Base",img:"godslayers_greatsword_colossal_sword_weapon"},
  {name:"Golden Order Greatsword",effect:"Greatsword – sacro, Erdtree magic",loc:"Cave of the Forlorn – boss reward",dlc:"Base",img:"golden_order_greatsword_weapon"},
  {name:"Grafted Blade Greatsword",effect:"Colossal – massive poise, skill Oath of Vengeance",loc:"Castle Morne – boss Leonine Misbegotten",dlc:"Base",img:"grafted_blade_greatsword_colossal_sword_weapon"},
  {name:"Greatsword",effect:"Colossal Sword – base ma devastante",loc:"Caelid – carro coperto a nordest",dlc:"Base",img:"greatsword_colossal_sword_weapon"},
  {name:"Hand of Malenia",effect:"Katana – skill Waterfowl Dance",loc:"Enia – Ricordo della Dea del Marciume",dlc:"Base",img:"hand_of_malenia_katana_weapon"},
  {name:"Loretta's War Sickle",effect:"Halberd – magia Caria",loc:"Loretta, Knight of Haligtree – boss reward",dlc:"Base",img:"lorettas_war_sickle_halberd_weapon"},
  {name:"Maliketh's Black Blade",effect:"Colossal Sword – riduce HP max del nemico",loc:"Enia – Ricordo della Black Blade",dlc:"Base",img:"malikeths_black_blade_colossal_sword_weapon"},
  {name:"Marais Executioner's Sword",effect:"Colossal – skill trapano, poise break",loc:"Shaded Castle – Elemer boss",dlc:"Base",img:"marais_executioners_sword_colossal_sword_weapon"},
  {name:"Meteoric Ore Blade",effect:"Katana – gravità + skill Gravitas",loc:"Caelid Waypoint Ruins – baule",dlc:"Base",img:"meteoric_ore_blade_katana_weapon"},
  {name:"Misericorde",effect:"Dagger – critical hit +140%",loc:"Stormveil Castle – armeria",dlc:"Base",img:"misericorde_dagger_weapon"},
  {name:"Mohgwyn's Sacred Spear",effect:"Spear – bloodflame, skill devastante",loc:"Enia – Ricordo del Blood Lord",dlc:"Base",img:"mohgwyns_sacred_spear_weapon"},
  {name:"Moonveil",effect:"Katana – magic slash skill invisibile",loc:"Gael Tunnel – Magma Wyrm boss",dlc:"Base",img:"moonveil_katana_weapon"},
  {name:"Morgott's Cursed Sword",effect:"Curved Greatsword – bleed sacro",loc:"Enia – Ricordo dell'Omen King",dlc:"Base",img:"morgotts_cursed_sword_curved_greatsword_weapon"},
  {name:"Nagakiba",effect:"Katana – lunga portata, bleed",loc:"Bloody Finger Hunter Yura – drop",dlc:"Base",img:"nagakiba_katana_weapon"},
  {name:"Reduvia",effect:"Dagger – bleed, skill proiettile sangue",loc:"Murkwater Cave – Bloody Finger Nerijus",dlc:"Base",img:"reduvia_dagger_weapon"},
  {name:"Rivers of Blood",effect:"Katana – bleed, skill Corpse Piler",loc:"Mountaintops – Okina NPC drop",dlc:"Base",img:"rivers_of_blood_katana_weapon"},
  {name:"Ruins Greatsword",effect:"Colossal Sword – gravità, skill Wave of Destruction",loc:"Redmane Castle – boss doppio",dlc:"Base",img:"ruins_greatsword_colossal_sword_weapon"},
  {name:"Sacred Relic Sword",effect:"Greatsword – skill perfetta per farm rune",loc:"Elden Beast – boss reward",dlc:"Base",img:"sacred_relic_sword_greatsword_weapon"},
  {name:"Starscourge Greatsword",effect:"Colossal Sword – gravità doppia",loc:"Enia – Ricordo dello Starscourge",dlc:"Base",img:"starscourge_greatsword_colossal_sword_weapon"},
  {name:"Sword of Night and Flame",effect:"Straight Sword – skill fuoco e magia",loc:"Caria Manor – baule",dlc:"Base",img:"sword_of_night_and_flame_straight_sword_weapon"},
  {name:"Treespear",effect:"Spear – sacro, split damage",loc:"Ainsel River Main – baule",dlc:"Base",img:"treespear_spear_weapon"},
  {name:"Uchigatana",effect:"Katana – classe Samurai / starter versatile",loc:"Deathtouched Catacombs / partenza Samurai",dlc:"Base",img:"uchigatana_katana_weapon"},
  {name:"Winged Scythe",effect:"Reaper – sacro, impedisce la guarigione",loc:"Tombsward Ruins – baule sotterraneo",dlc:"Base",img:"winged_scythe_reaper_weapon"},
  {name:"Euporia",effect:"Twinblade – sacro, danza degli dei",loc:"SotE – Enir-Ilim area finale",dlc:"SotE",img:"euporia_twinblade_weapon"},
  {name:"Sword of Night",effect:"Straight Sword – notte, SotE",loc:"Cerulean Coast – SotE",dlc:"SotE",img:"sword_of_night_straight_sword_weapon"},
  {name:"Malenia's Blade",effect:"Katana – lifesteal su ogni hit",loc:"Enia – Ricordo della Dea del Marciume",dlc:"Base",img:"hand_of_malenia_katana_weapon"},
],
armor:[
  {name:"Ansbach's Helm",effect:"Set SotE leggero elegante",loc:"SotE – Ansbach quest reward",dlc:"SotE",img:"answbachs_helm_armor_elden_ring_wiki"},
  {name:"Ansbach's Armor",effect:"Set SotE leggero elegante",loc:"SotE – Ansbach quest reward",dlc:"SotE",img:"answbachs_armor_elden_ring_wiki"},
  {name:"Ansbach's Gauntlets",effect:"Set SotE leggero elegante",loc:"SotE – Ansbach quest reward",dlc:"SotE",img:"answbachs_gauntlets_armor_elden_ring_wiki"},
  {name:"Ansbach's Greaves",effect:"Set SotE leggero elegante",loc:"SotE – Ansbach quest reward",dlc:"SotE",img:"answbachs_greaves_armor_elden_ring_wiki"},
  {name:"Black Knife Hood",effect:"Set Black Knife – silenzia i passi",loc:"Black Knife Assassin drops (solo di notte)",dlc:"Base",img:"black_knife_hood_armor_elden_ring_wiki"},
  {name:"Black Knife Armor",effect:"Set Black Knife – silenzia i passi",loc:"Black Knife Assassin drops (solo di notte)",dlc:"Base",img:"black_knife_armor_elden_ring_wiki"},
  {name:"Black Knife Gauntlets",effect:"Set Black Knife – silenzia i passi",loc:"Black Knife Assassin drops",dlc:"Base",img:"black_knife_gauntlets_armor_elden_ring_wiki"},
  {name:"Black Knife Greaves",effect:"Set Black Knife – silenzia i passi",loc:"Black Knife Assassin drops",dlc:"Base",img:"black_knife_greaves_armor_elden_ring_wiki"},
  {name:"Blaidd's Helm",effect:"Set Blaidd – alto peso e difesa",loc:"Ranni quest – Blaidd drop (ostile)",dlc:"Base",img:"blaids_helm_armor_elden_ring_wiki"},
  {name:"Blaidd's Armor",effect:"Set Blaidd – alto peso e difesa",loc:"Ranni quest – Blaidd drop (ostile)",dlc:"Base",img:"blaids_armor_elden_ring_wiki"},
  {name:"Blaidd's Gauntlets",effect:"Set Blaidd – alto peso e difesa",loc:"Ranni quest – Blaidd drop (ostile)",dlc:"Base",img:"blaids_gauntlets_armor_elden_ring_wiki"},
  {name:"Blaidd's Greaves",effect:"Set Blaidd – alto peso e difesa",loc:"Ranni quest – Blaidd drop (ostile)",dlc:"Base",img:"blaids_greaves_armor_elden_ring_wiki"},
  {name:"Bull-Goat Helm",effect:"Set Bull-Goat – massima poise",loc:"Great Tunnel – Patches quest",dlc:"Base",img:"bull-goat_helm_armor_elden_ring_wiki"},
  {name:"Bull-Goat Armor",effect:"Set Bull-Goat – massima poise",loc:"Great Tunnel – Patches quest",dlc:"Base",img:"bull-goat_armor_elden_ring_wiki"},
  {name:"Bull-Goat Gauntlets",effect:"Set Bull-Goat – massima poise",loc:"Great Tunnel – Patches quest",dlc:"Base",img:"bull-goat_gauntlets_armor_elden_ring_wiki"},
  {name:"Bull-Goat Greaves",effect:"Set Bull-Goat – massima poise",loc:"Great Tunnel – Patches quest",dlc:"Base",img:"bull-goat_greaves_armor_elden_ring_wiki"},
  {name:"Crucible Axe Helm",effect:"Set Crucible Axe – aspetto drago primordiale",loc:"Auriza Hero's Grave – boss reward",dlc:"Base",img:"crucible_axe_helm_armor_elden_ring_wiki"},
  {name:"Crucible Axe Armor",effect:"Set Crucible Axe – aspetto drago primordiale",loc:"Auriza Hero's Grave – boss reward",dlc:"Base",img:"crucible_axe_armor_elden_ring_wiki"},
  {name:"Crucible Axe Gauntlets",effect:"Set Crucible Axe",loc:"Auriza Hero's Grave – boss reward",dlc:"Base",img:"crucible_axe_gauntlets_armor_elden_ring_wiki"},
  {name:"Crucible Axe Greaves",effect:"Set Crucible Axe",loc:"Auriza Hero's Grave – boss reward",dlc:"Base",img:"crucible_axe_greaves_armor_elden_ring_wiki"},
  {name:"Fire Knight Helm",effect:"Set Fire Knight – armatura SotE",loc:"SotE – Fire Knights drop",dlc:"SotE",img:"fire_knight_helm_armor_elden_ring_wiki"},
  {name:"Fire Knight Armor",effect:"Set Fire Knight – armatura SotE",loc:"SotE – Fire Knights drop",dlc:"SotE",img:"fire_knight_armor_elden_ring_wiki"},
  {name:"Fire Knight Gauntlets",effect:"Set Fire Knight – armatura SotE",loc:"SotE – Fire Knights drop",dlc:"SotE",img:"fire_knight_gauntlets_armor_elden_ring_wiki"},
  {name:"Fire Knight Greaves",effect:"Set Fire Knight – armatura SotE",loc:"SotE – Fire Knights drop",dlc:"SotE",img:"fire_knight_greaves_armor_elden_ring_wiki"},
  {name:"Malenia's Helm",effect:"Set Malenia – leggero, +Arcane",loc:"Millicent quest – area Malenia",dlc:"Base",img:"malenias_helm_armor_elden_ring_wiki"},
  {name:"Malenia's Armor",effect:"Set Malenia – leggero, +Arcane",loc:"Enia dopo Malenia",dlc:"Base",img:"malenias_armor_elden_ring_wiki"},
  {name:"Malenia's Gauntlet",effect:"Set Malenia – leggero, +Arcane",loc:"Enia dopo Malenia",dlc:"Base",img:"malenias_gauntlet_armor_elden_ring_wiki"},
  {name:"Malenia's Greaves",effect:"Set Malenia – leggero, +Arcane",loc:"Enia dopo Malenia",dlc:"Base",img:"malenias_greaves_armor_elden_ring_wiki"},
  {name:"Raging Wolf Helm",effect:"Set Raging Wolf – aspetto lupesco",loc:"Volcano Manor – Rya quest",dlc:"Base",img:"raging_wolf_helm_armor_elden_ring_wiki"},
  {name:"Raging Wolf Armor",effect:"Set Raging Wolf – aspetto lupesco",loc:"Volcano Manor – Rya quest",dlc:"Base",img:"raging_wolf_armor_elden_ring_wiki"},
  {name:"Raging Wolf Gauntlets",effect:"Set Raging Wolf – aspetto lupesco",loc:"Volcano Manor – Rya quest",dlc:"Base",img:"raging_wolf_gauntlets_armor_elden_ring_wiki"},
  {name:"Raging Wolf Greaves",effect:"Set Raging Wolf – aspetto lupesco",loc:"Volcano Manor – Rya quest",dlc:"Base",img:"raging_wolf_greaves_armor_elden_ring_wiki"},
  {name:"Radahn's Lion Helm",effect:"Set Radahn – massiccio e iconico",loc:"Twin Maiden Husks dopo Radahn",dlc:"Base",img:"radahns_lion_helm_armor_elden_ring_wiki"},
  {name:"Radahn's Lion Armor",effect:"Set Radahn – massiccio e iconico",loc:"Twin Maiden Husks dopo Radahn",dlc:"Base",img:"radahns_lion_armor_elden_ring_wiki"},
  {name:"Veteran's Helm",effect:"Set Veteran – pesante, alta difesa",loc:"Commander Niall – boss reward",dlc:"Base",img:"veterans_helm_armor_elden_ring_wiki"},
  {name:"Veteran's Armor",effect:"Set Veteran – pesante, alta difesa",loc:"Commander Niall – boss reward",dlc:"Base",img:"veterans_armor_elden_ring_wiki"},
  {name:"Veteran's Gauntlets",effect:"Set Veteran – pesante, alta difesa",loc:"Commander Niall – boss reward",dlc:"Base",img:"veterans_gauntlets_armor_elden_ring_wiki"},
  {name:"Veteran's Greaves",effect:"Set Veteran – pesante, alta difesa",loc:"Commander Niall – boss reward",dlc:"Base",img:"veterans_greaves_armor_elden_ring_wiki"},
  {name:"White Reed Helm",effect:"Set White Reed – stile ninja katana",loc:"Spiritspring vicino Freezing Lake",dlc:"Base",img:"white_reed_helm_armor_elden_ring_wiki"},
  {name:"White Reed Armor",effect:"Set White Reed – stile ninja katana",loc:"Spiritspring vicino Freezing Lake",dlc:"Base",img:"white_reed_armor_elden_ring_wiki"},
  {name:"White Reed Gauntlets",effect:"Set White Reed – stile ninja katana",loc:"Spiritspring vicino Freezing Lake",dlc:"Base",img:"white_reed_gauntlets_armor_elden_ring_wiki"},
  {name:"White Reed Greaves",effect:"Set White Reed – stile ninja katana",loc:"Spiritspring vicino Freezing Lake",dlc:"Base",img:"white_reed_greaves_armor_elden_ring_wiki"},
],
sorceries:[
  {name:"Adula's Moonblade",effect:"Lama crescente di freddo magico",loc:"Moonfolk Ruins / Ranni quest",dlc:"Base",img:"adulas_moonblade_sorcery_elden_ring_wiki_guide"},
  {name:"Cannon of Haima",effect:"Grande palla esplosiva di glintstone",loc:"Converted Fringe Tower – baule",dlc:"Base",img:"cannon_of_haima_sorcery_elden_ring_wiki_guide"},
  {name:"Carian Greatsword",effect:"Crea greatsword e spacca dall'alto",loc:"Carian Study Hall – baule",dlc:"Base",img:"carian_greatsword_sorcery_elden_ring_wiki_guide"},
  {name:"Carian Phalanx",effect:"Chiama lame magiche orbitanti difensive",loc:"Converted Tower – baule",dlc:"Base",img:"carian_phalanx_sorcery_elden_ring_wiki_guide"},
  {name:"Carian Piercer",effect:"Trafigge con una spada gigante",loc:"Testu's Rise – puzzle",dlc:"Base",img:"carian_piercer_sorcery_elden_ring_wiki_guide"},
  {name:"Carian Retaliation",effect:"Para e rilancia frecce magiche",loc:"Renna's Rise – baule",dlc:"Base",img:"carian_retaliation_sorcery_elden_ring_wiki_guide"},
  {name:"Carian Slicer",effect:"Fendente rapido con lama magica",loc:"Sorcerer Rogier – Roundtable Hold",dlc:"Base",img:"carian_slicer_sorcery_elden_ring_wiki_guide"},
  {name:"Comet",effect:"Cometa magica ad alta velocità",loc:"Caelid – Caelid Waypoint baule",dlc:"Base",img:"comet_sorcery_elden_ring_wiki_guide"},
  {name:"Comet Azur",effect:"Enorme raffica di comete (Legg.)",loc:"Mt. Gelmir – Primeval Sorcerer Azur",dlc:"Base",img:"comet_azur_sorcery_elden_ring_wiki_guide"},
  {name:"Crystal Torrent",effect:"Pioggia continua di cristalli",loc:"Altus Plateau – Crystalian boss",dlc:"Base",img:"crystal_torrent_sorcery_elden_ring_wiki_guide"},
  {name:"Eternal Darkness",effect:"Buco nero risucchia proiettili",loc:"Volcano Manor – quest",dlc:"Base",img:"eternal_darkness_sorcery_elden_ring_wiki_guide"},
  {name:"Founding Rain of Stars",effect:"Pioggia di stelle infinita dall'alto",loc:"Heretical Rise – baule",dlc:"Base",img:"founding_rain_of_stars_sorcery_elden_ring_wiki_guide"},
  {name:"Freezing Mist",effect:"Nebbia gelida in avanti",loc:"Caria Manor – Loretta boss reward",dlc:"Base",img:"freezing_mist_sorcery_elden_ring_wiki_guide"},
  {name:"Full Moon of Nokstella",effect:"Spara una luna blu potente",loc:"Nokstella – baule",dlc:"Base",img:"full_moon_of_nokstella_sorcery_elden_ring_wiki_guide"},
  {name:"Gavel of Haima",effect:"Bastone di gravità colpisce il suolo",loc:"Converted Fringe Tower – boss sorcerer",dlc:"Base",img:"gavel_of_haima_sorcery_elden_ring_wiki_guide"},
  {name:"Glintstone Icecrag",effect:"Cometa magica ghiacciata",loc:"Caria Manor – baule",dlc:"Base",img:"glintstone_icecrag_sorcery_elden_ring_wiki_guide"},
  {name:"Glintstone Pebble",effect:"Proiettile glintstone base",loc:"Sorcerer Rogier / Merchant Kale",dlc:"Base",img:"glintstone_pebble_sorcery_elden_ring_wiki_guide"},
  {name:"Gravity Well",effect:"Attira nemici con la gravità",loc:"Hermit Village – Demi-Human Queen boss",dlc:"Base",img:"gravity_well_sorcery_elden_ring_wiki_guide"},
  {name:"Greatblade Phalanx",effect:"Greatsword magiche orbitanti",loc:"Seluvis's Rise – torre mago",dlc:"Base",img:"greatblade_phalanx_sorcery_elden_ring_wiki_guide"},
  {name:"Loretta's Greatbow",effect:"Grande freccia magica",loc:"Loretta boss Caria Manor – reward",dlc:"Base",img:"lorettas_greatbow_sorcery_elden_ring_wiki_guide"},
  {name:"Loretta's Mastery",effect:"Versione potenziata di Loretta's Greatbow",loc:"Loretta, Knight of Haligtree boss",dlc:"Base",img:"lorettas_mastery_sorcery_elden_ring_wiki_guide"},
  {name:"Magic Downpour",effect:"Pioggia di colpi magici",loc:"Converted Fringe Tower – baule in cima",dlc:"Base",img:"magic_downpour_sorcery_elden_ring_wiki_guide"},
  {name:"Meteorite",effect:"Tre grandi meteoriti piovono",loc:"Limgrave – dietro puzzle masso",dlc:"Base",img:"meteorite_sorcery_elden_ring_wiki_guide"},
  {name:"Meteorite of Astel",effect:"Raffica di piccoli meteoriti",loc:"Astel, Stars of Darkness – boss reward",dlc:"Base",img:"meteorite_of_astel_sorcery_elden_ring_wiki_guide"},
  {name:"Night Comet",effect:"Cometa invisibile ai nemici",loc:"Sellia, Town of Sorcery – baule",dlc:"Base",img:"night_comet_sorcery_elden_ring_wiki_guide"},
  {name:"Night Shard",effect:"Frammento invisibile veloce",loc:"Sellia, Town of Sorcery – baule",dlc:"Base",img:"night_shard_sorcery_elden_ring_wiki_guide"},
  {name:"Oracle Bubbles",effect:"Bolle magiche rimbalzanti",loc:"Siofra River – baule",dlc:"Base",img:"oracle_bubbles_sorcery_elden_ring_wiki_guide"},
  {name:"Ranni's Dark Moon",effect:"Luna oscura riduce negazione magica",loc:"Chelona's Rise – tre tartarughe",dlc:"Base",img:"rannis_dark_moon_sorcery_elden_ring_wiki_guide"},
  {name:"Rennala's Full Moon",effect:"Luna piena riduce negazione magica (Legg.)",loc:"Enia – Ricordo della Regina Luna",dlc:"Base",img:"rennalas_full_moon_sorcery_elden_ring_wiki_guide"},
  {name:"Rock Sling",effect:"Lancia tre massi con gravità",loc:"Street of Sages Ruins – baule sotterraneo",dlc:"Base",img:"rock_sling_sorcery_elden_ring_wiki_guide"},
  {name:"Stars of Ruin",effect:"12 stelle guidate (Legg.)",loc:"Master Lusat – Sellia Hideaway reward",dlc:"Base",img:"stars_of_ruin_sorcery_elden_ring_wiki_guide"},
  {name:"Terra Magica",effect:"Crea pozza che potenzia le sorcery",loc:"Academy Crystal Cave – boss reward",dlc:"Base",img:"terra_magica_sorcery_elden_ring_wiki_guide"},
  {name:"Vortex of Lunacy",effect:"Vortice spirale di follia",loc:"SotE – area Belurat",dlc:"SotE",img:"vortex_of_lunacy_sorcery_elden_ring_wiki_guide"},
  {name:"Miriam's Vanishing",effect:"Teleporta indietro e spara dardo magico",loc:"Converted Tower – puzzle",dlc:"Base",img:"miriams_vanishing_sorcery_elden_ring_wiki_guide"},
  {name:"Trina's Mist",effect:"Nebbia che induce sonno",loc:"SotE – Count Ymir area",dlc:"SotE",img:"trinas_mist_sorcery_elden_ring_wiki_guide"},
],
incantations:[
  {name:"Ancient Dragons' Lightning Spear",effect:"Lancia fulmine dei dragoni antichi",loc:"Ancient Dragon Senessax / Farum Azula",dlc:"Base",img:"ancient_dragons_lightning_spear_incantation_elden_ring_wiki_guide"},
  {name:"Aspects of the Crucible: Breath",effect:"Respiro di fuoco conico",loc:"Stormveil – Crucible Knight Ordovis boss",dlc:"Base",img:"aspects_of_the_crucible_breath_incantation_elden_ring_wiki_guide"},
  {name:"Aspects of the Crucible: Horns",effect:"Carica con le corna del Crucible",loc:"Auriza Hero's Grave – Crucible Knight",dlc:"Base",img:"aspects_of_the_crucible_horns_incantation_elden_ring_wiki_guide"},
  {name:"Aspects of the Crucible: Tail",effect:"Frusta con la coda bestiale",loc:"Stormhill Evergaol – Crucible Knight",dlc:"Base",img:"aspects_of_the_crucible_tail_incantation_elden_ring_wiki_guide"},
  {name:"Barrier of Gold",effect:"Scudo dorato che riduce danno magico",loc:"Erdtree Avatar – Mountaintops",dlc:"Base",img:"barrier_of_gold_incantation_elden_ring_wiki_guide"},
  {name:"Black Blade",effect:"Lama dorata riduce HP max del nemico",loc:"Enia – Ricordo della Black Blade",dlc:"Base",img:"black_blade_incantation_elden_ring_wiki_guide"},
  {name:"Black Flame",effect:"Lancia fiamma nera che brucia HP",loc:"Godslayer's Evergaol – boss",dlc:"Base",img:"black_flame_incantation_elden_ring_wiki_guide"},
  {name:"Black Flame Blade",effect:"Riveste l'arma di fiamma nera",loc:"Sorcerer Rogier / Volcano Manor",dlc:"Base",img:"black_flame_blade_incantation_elden_ring_wiki_guide"},
  {name:"Bloodboon",effect:"Disperde sangue dalle dita",loc:"Mohgwyn Palace – Sanguine Noble drop",dlc:"Base",img:"bloodboon_incantation_elden_ring_wiki_guide"},
  {name:"Bloodflame Blade",effect:"Riveste l'arma di bloodflame",loc:"Rose Church – White Mask Varré quest",dlc:"Base",img:"bloodflame_blade_incantation_elden_ring_wiki_guide"},
  {name:"Bloodflame Talons",effect:"Artigli di bloodflame",loc:"Mohgwyn Palace – baule",dlc:"Base",img:"bloodflame_talons_incantation_elden_ring_wiki_guide"},
  {name:"Burn, O Flame!",effect:"Colonna di fiamma in avanti",loc:"Volcano Manor – Demi-Human Queen Maggie",dlc:"Base",img:"burn_o_flame_incantation_elden_ring_wiki_guide"},
  {name:"Catch Flame",effect:"Rapida fiamma dal palmo",loc:"Tutorial / Merchant Kale",dlc:"Base",img:"catch_flame_incantation_elden_ring_wiki_guide"},
  {name:"Dragonfire",effect:"Respiro di fuoco – Dragon Communion",loc:"Dragon Communion Altar – Agheel",dlc:"Base",img:"dragonfire_incantation_elden_ring_wiki_guide"},
  {name:"Dragonmaw",effect:"Morso del drago ad alto danno",loc:"Dragon Communion – Elder Dragon Greyoll",dlc:"Base",img:"dragonmaw_incantation_elden_ring_wiki_guide"},
  {name:"Elden Stars",effect:"Grande sfera di luce sacra",loc:"Deeproot Depths – baule",dlc:"Base",img:"elden_stars_incantation_elden_ring_wiki_guide"},
  {name:"Electrify Armament",effect:"Riveste l'arma di fulmine",loc:"Leyndell – baule dopo Draconic Tree Sentinel",dlc:"Base",img:"electrify_armament_incantation_elden_ring_wiki_guide"},
  {name:"Erdtree Heal",effect:"Cura grande quantità di HP vicino",loc:"Erdtree Avatar drops",dlc:"Base",img:"erdtree_heal_incantation_elden_ring_wiki_guide"},
  {name:"Flame of the Fell God",effect:"Lenta fiamma che esplode",loc:"Enia – Ricordo del Fell Omen (Margit)",dlc:"Base",img:"flame_of_the_fell_god_incantation_elden_ring_wiki_guide"},
  {name:"Flame Sling",effect:"Lancia palla di fuoco",loc:"Merchant Kale – acquisto economico",dlc:"Base",img:"flame_sling_incantation_elden_ring_wiki_guide"},
  {name:"Flame, Grant Me Strength",effect:"+danno fuoco e fisico temporaneo",loc:"Fort Gael – cadavere dietro Grafted Scion",dlc:"Base",img:"flame_grant_me_strength_incantation_elden_ring_wiki_guide"},
  {name:"Fortissax's Lightning Spear",effect:"Due fulmini e affondo",loc:"Enia – Ricordo del Lichdragon Fortissax",dlc:"Base",img:"fortissaxs_lightning_spear_incantation_elden_ring_wiki_guide"},
  {name:"Frenzied Burst",effect:"Raggio preciso di fiamma della follia",loc:"Frenzied Flame Proscription – Three Fingers",dlc:"Base",img:"frenzied_burst_incantation_elden_ring_wiki_guide"},
  {name:"Giant Flame Shrouding",effect:"Aumenta notevolmente il danno fuoco",loc:"SotE – area Giant Flame",dlc:"SotE",img:"giant_flame_shrouding_incantation_elden_ring_wiki_guide"},
  {name:"Giantsflame Take Thee",effect:"Lancia enorme palla esplosiva",loc:"Foot of the Forge – baule",dlc:"Base",img:"giantsflame_take_thee_incantation_elden_ring_wiki_guide"},
  {name:"Golden Vow",effect:"+ATK e difesa vicino (incantazione)",loc:"Corpse-Stench Shack – Mt. Gelmir",dlc:"Base",img:"golden_vow_incantation_elden_ring_wiki_guide"},
  {name:"Greyoll's Roar",effect:"Ruggito drago indebolisce nemici",loc:"Dragon Communion – Elder Dragon Greyoll",dlc:"Base",img:"greyolls_roar_incantation_elden_ring_wiki_guide"},
  {name:"Howl of Shabriri",effect:"Accumula follia nei nemici vicini",loc:"Frenzied Flame Village – Shabriri NPC",dlc:"Base",img:"howl_of_shabriri_incantation_elden_ring_wiki_guide"},
  {name:"Inescapable Frenzy",effect:"Afferra e induce follia",loc:"Frenzied Flame Proscription – three fingers",dlc:"Base",img:"inescapable_frenzy_incantation_elden_ring_wiki_guide"},
  {name:"Law of Causality",effect:"Contrattacca con sacro dopo più colpi ricevuti",loc:"East Windmill Pasture – cadavere",dlc:"Base",img:"law_of_causality_incantation_elden_ring_wiki_guide"},
  {name:"Lightning Spear",effect:"Lancia lancia dorata di fulmine",loc:"Stormveil Castle / Farum area",dlc:"Base",img:"lightning_spear_incantation_elden_ring_wiki_guide"},
  {name:"Litany of Proper Death",effect:"Distrugge scheletri, impedisce la rinascita",loc:"Auriza Side Tomb – baule",dlc:"Base",img:"litany_of_proper_death_incantation_elden_ring_wiki_guide"},
  {name:"Lord's Heal",effect:"Cura enormemente HP in area",loc:"Haligtree – Erdtree Avatar drop",dlc:"Base",img:"lords_heal_incantation_elden_ring_wiki_guide"},
  {name:"O, Flame!",effect:"Onda di fiamma lungo il suolo",loc:"Fire Monk drops",dlc:"Base",img:"o_flame_incantation_elden_ring_wiki_guide"},
  {name:"Pest Threads",effect:"Fili di marciume scarlatto",loc:"Gowry merchant",dlc:"Base",img:"pest_threads_incantation_elden_ring_wiki_guide"},
  {name:"Placidusax's Ruin",effect:"Doppio raggio drago devastante",loc:"Enia – Ricordo del Dragonlord",dlc:"Base",img:"placidusaxs_ruin_incantation_elden_ring_wiki_guide"},
  {name:"Poison Armament",effect:"Riveste l'arma di veleno",loc:"Mercanti vari",dlc:"Base",img:"poison_armament_incantation_elden_ring_wiki_guide"},
  {name:"Rotten Breath",effect:"Respiro di marciume scarlatto",loc:"Dragon Communion – Ekzykes drop",dlc:"Base",img:"rotten_breath_incantation_elden_ring_wiki_guide"},
  {name:"Scarlet Aeonia",effect:"Fiore esplosivo di marciume scarlatto",loc:"Enia – Ricordo della Dea del Marciume",dlc:"Base",img:"scarlet_aeonia_incantation_elden_ring_wiki_guide"},
  {name:"Shadows of Death",effect:"Fulmini d'ombra dall'alto",loc:"SotE – area boss Messmer",dlc:"SotE",img:"shadows_of_death_incantation_elden_ring_wiki_guide"},
  {name:"Stone of Gurranq",effect:"Lancia roccia rimbalzante",loc:"Bestial Sanctum – Gurranq (Deathroot)",dlc:"Base",img:"stone_of_gurranq_incantation_elden_ring_wiki_guide"},
  {name:"Swarm of Flies",effect:"Sciame di mosche sanguinanti (bleed)",loc:"Mohgwyn Palace – cadavere in grotta",dlc:"Base",img:"swarm_of_flies_incantation_elden_ring_wiki_guide"},
  {name:"The Flame of Frenzy",effect:"Raggio di fiamma della follia",loc:"Callu Baptismal Church – baule",dlc:"Base",img:"the_flame_of_frenzy_incantation_elden_ring_wiki_guide"},
  {name:"Thunderbolt",effect:"Potente fulmine dall'alto",loc:"Dragon Cult Knight drops",dlc:"Base",img:"thunderbolt_incantation_elden_ring_wiki_guide"},
  {name:"Urgent Heal",effect:"Cura moderata rapida",loc:"Merchant Kale / chiese – early game",dlc:"Base",img:"urgent_heal_incantation_elden_ring_wiki_guide"},
  {name:"Vyke's Dragonbolt",effect:"Si carica e chiama fulmini",loc:"Festering Fingerprint Vyke – NPC drop",dlc:"Base",img:"vykes_dragonbolt_incantation_elden_ring_wiki_guide"},
  {name:"Wrath of Gold",effect:"Onda d'urto dorata",loc:"Leyndell Royal Capital – mercante",dlc:"Base",img:"wrath_of_gold_incantation_elden_ring_wiki_guide"},
  {name:"Darkness",effect:"Orb che disturba la visione",loc:"SotE – Abyssal Woods",dlc:"SotE",img:"darkness_incantation_elden_ring_wiki_guide"},
  {name:"Frenzied Eruption",effect:"Fiamma della follia erutta dal suolo",loc:"SotE – Abyssal Woods",dlc:"SotE",img:"frenzied_eruption_incantation_elden_ring_wiki_guide"},
  {name:"Mass of Putrescence",effect:"Lancia palla di marciume pestilenziale",loc:"SotE – Ulcerated Tree Spirit drop",dlc:"SotE",img:"mass_of_putrescence_incantation_elden_ring_wiki_guide"},
],
spiritashes:[
  {name:"Ancient Dragon Knight Kristoff Ashes",effect:"Cavaliere potente con fulmine drago",loc:"Auriza Hero's Grave – boss reward",dlc:"Base",img:"ancient_dragon_knight_kristoff_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Banished Knight Oleg Ashes",effect:"Cavaliere espulso aggressivo",loc:"Fringefolk Hero's Grave – boss reward",dlc:"Base",img:"banished_knight_oleg_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Black Knife Tiche Ashes",effect:"Assassina Black Knife velocissima (Legg.)",loc:"Ringleader's Evergaol – boss reward",dlc:"Base",img:"black_knife_tiche_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Cleanrot Knight Finlay Ashes",effect:"Cavaliere Cleanrot (Legg.)",loc:"Elphael – cadavere",dlc:"Base",img:"cleanrot_knight_finlay_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Divine Bird Warrior Ashes",effect:"Guerriero uccello divino SotE",loc:"SotE – Jagged Peak area",dlc:"SotE",img:"divine_bird_warrior_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Dung Eater Puppet Ashes",effect:"Seluvis quest – Dung Eater",loc:"Seluvis quest – richiede pozione",dlc:"Base",img:"dung_eater_puppet_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Fanged Imp Ashes",effect:"Due imp con zanne",loc:"Roundtable Hold – mercante iniziale",dlc:"Base",img:"fanged_imp_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Fire Prelate Ashes",effect:"Prelato del fuoco con flagello",loc:"Giants' Mountaintop – cadavere Prelate",dlc:"Base",img:"fire_prelate_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Greatshield Soldier Ashes",effect:"Quattro soldati con scudo grande",loc:"Nokron – Night's Sacred Ground",dlc:"Base",img:"greatshield_soldier_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Horned Warrior Ashes",effect:"Guerriero cornuto SotE",loc:"SotE – Temple Town Ruins",dlc:"SotE",img:"horned_warrior_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Jellyfish Ashes",effect:"Medusa che spruzza acido",loc:"Stormhill – Irina quest cadavere",dlc:"Base",img:"jellyfish_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Knight Bernahl Ashes",effect:"Cavaliere Bernahl",loc:"Volcano Manor – Bernahl quest reward",dlc:"Base",img:"knight_bernahl_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Lhutel the Headless Ashes",effect:"Cavaliere spettrale teleportante (Legg.)",loc:"Tombsward Catacombs – boss reward",dlc:"Base",img:"lhutel_the_headless_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Lone Wolf Ashes",effect:"Tre lupi – regalo di Renna",loc:"Renna's gift / Kalé vendor",dlc:"Base",img:"lone_wolf_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Messmer Soldier Ashes",effect:"Soldato di Messmer SotE",loc:"SotE – Shadow Keep",dlc:"SotE",img:"messmer_soldier_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Mimic Tear Ashes",effect:"Copia il tuo equipaggiamento (Legg.)",loc:"Nokron – Stonesword Key baule",dlc:"Base",img:"mimic_tear_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Nightmaiden & Swordstress Ashes",effect:"Duo potente (Legg.)",loc:"Nokstella – Ghost boss reward",dlc:"Base",img:"nightmaiden_and_swordstress_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Omenkiller Rollo Ashes",effect:"Omenkiller poderoso",loc:"Volcano Manor – Rya quest reward",dlc:"Base",img:"omenkiller_rollo_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Perfumer Tricia Ashes",effect:"Guaritrice healer (Legg.)",loc:"Unsightly Catacombs – boss reward",dlc:"Base",img:"perfumer_tricia_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Redmane Knight Ogha Ashes",effect:"Arciere Redmane (Legg.)",loc:"War-Dead Catacombs – boss reward",dlc:"Base",img:"redmane_knight_ogha_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Skeletal Bandit Ashes",effect:"Banditi scheletrici – si rialzano",loc:"Nokron ruins – baule",dlc:"Base",img:"skeletal_bandit_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Soldjars of Fortune Ashes",effect:"Piccoli guerrieri-barattolo",loc:"Volcano Manor – Alexander quest",dlc:"Base",img:"soldjars_of_fortune_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Spirit Jellyfish Ashes",effect:"Medusa fantasma economica",loc:"Mercante a Stormhill",dlc:"Base",img:"spirit_jellyfish_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Stormhawk Deenh Ashes",effect:"Falco attaccante",loc:"Chapel of Anticipation – baule",dlc:"Base",img:"stormhawk_deenh_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Twinsage Sorcerer Ashes",effect:"Due maghi gemelli",loc:"Raya Lucaria Academy – baule",dlc:"Base",img:"twinsage_sorcerer_spirit_ashes_elden_ring_wiki_guide"},
  {name:"Avionette Apostle Ashes",effect:"Apostola volante SotE",loc:"SotE – Belurat area",dlc:"SotE",img:"avionette_soldier_ashes_spirit_elden_ring_wiki_guide"},
  {name:"Wandering Noble Ashes",effect:"Cinque nobili fantasma – economici",loc:"Vari – più economici",dlc:"Base",img:"wandering_noble_ashes_spirit_elden_ring_wiki_guide"},
],
shields:[
  {name:"Brass Shield",effect:"Scudo medio – alta negazione fisica",loc:"Godrick Soldiers – Stormveil",dlc:"Base",img:"brass_shield_shields_elden_ring_wiki_guide"},
  {name:"Dragon Towershield",effect:"Scudo grande SotE – molto potente",loc:"SotE – Ancient Ruins area",dlc:"SotE",img:"dragon_towershield_shields_elden_ring_wiki_guide"},
  {name:"Eclipse Crest Heater Shield",effect:"Scudo piccolo – resistenza sacra",loc:"Castle Sol – baule",dlc:"Base",img:"eclipse_crest_heater_shield_shields_elden_ring_wiki_guide"},
  {name:"Erdtree Greatshield",effect:"Scudo grande – skill riflette danno sacro",loc:"Consecrated Snowfield – baule",dlc:"Base",img:"erdtree_greatshield_shields_elden_ring_wiki_guide"},
  {name:"Golden Epitaph",effect:"Scudo medio – Rune bonus lieve",loc:"Auriza Hero's Grave",dlc:"Base",img:"golden_epitaph_straight_sword_weapon"},
  {name:"Haligtree Crest Greatshield",effect:"Scudo grande – protezione completa",loc:"Elphael – baule",dlc:"Base",img:"haligtree_crest_greatshield_shields_elden_ring_wiki_guide"},
  {name:"Jellyfish Shield",effect:"Scudo grande – skill potenzia HP alleati",loc:"Weeping Peninsula – grotta",dlc:"Base",img:"jellyfish_shield_shields_elden_ring_wiki_guide"},
  {name:"One-Eyed Shield",effect:"Scudo grande – skill lancia palla di fuoco",loc:"Redmane Castle – boss Godrick Knight",dlc:"Base",img:"one-eyed_shield_shields_elden_ring_wiki_guide"},
  {name:"Scorpion Kite Shield",effect:"Scudo medio – veleno al contrattacco",loc:"Volcano Manor – baule",dlc:"Base",img:"scorpion_kite_shield_shields_elden_ring_wiki_guide"},
  {name:"Shield of the Guilty",effect:"Scudo piccolo – bleed al contrattacco",loc:"Roundtable Hold – negozio",dlc:"Base",img:"shield_of_the_guilty_shields_elden_ring_wiki_guide"},
  {name:"Silver Mirrorshield",effect:"Scudo medio – riflette la magia",loc:"Raya Lucaria – baule",dlc:"Base",img:"silver_mirrorshield_shields_elden_ring_wiki_guide"},
  {name:"Stone-Sheathed Sword",effect:"Scudo grande – versatile combo scudo-spada",loc:"Nokron – Night's Sacred Ground",dlc:"Base",img:"stone-sheathed_sword_straight_sword_weapon"},
  {name:"Visage Shield",effect:"Scudo grande – skill respiro di gravità",loc:"Fort Laiedd – baule",dlc:"Base",img:"visage_shield_shields_elden_ring_wiki_guide"},
  {name:"Blue-Gold Kite Shield",effect:"Scudo medio SotE – emblema Erdtree",loc:"SotE – Castle Ensis baule",dlc:"SotE",img:"blue-gold_kite_shield_shields_elden_ring_wiki_guide"},
  {name:"Pearl Shield",effect:"Scudo medio SotE – alta negazione magica",loc:"SotE – Taylew's Ruined Forge",dlc:"SotE",img:"pearl_shield_shields_elden_ring_wiki_guide"},
],
};
